export const ListFontFamily = {
    'Astro-City': 'Astro City',
    'Augie': 'Augie',
    'Canun': 'Canun',
    'Chancery': 'Chancery',
    'Chiller': 'Chiller',
    'Comic-1': 'Comic 1',
    'Comic-2': 'Comic 2',
    'Damn-Noisy-Kids': 'Damn Noisy Kids',
    'Dom': 'Dom',
    'Franko': 'Franko',
    'Getting-Angry': 'Getting Angry',
    'Grunge-Sans': 'Grunge Sans',
    'Jamai': 'Jamai',
    'Monster-Talking': 'Monster Talking',
    'Mysti': 'Mysti',
    'Oliver': 'Oliver',
    'Telephone': 'Telephone',
    'Wahroonga': 'Wahroonga',
    'Yikes': 'Yikes',
    'You-are-loved': 'You are loved',
};